import { Share } from '@capacitor/share';
import { Job } from '../types';

export const generateJobSummary = (job: Job): string => {
  const totalExpenses = job.expenses.reduce((sum, exp) => sum + exp.amount, 0);
  const remaining = job.estimatedPrice - totalExpenses;
  const percentageSpent = ((totalExpenses / job.estimatedPrice) * 100).toFixed(1);

  let summary = `📋 TRU JOB SUMMARY\n\n`;
  summary += `Job: ${job.title}\n`;
  summary += `Client: ${job.customerName}\n`;
  summary += `Due Date: ${new Date(job.dueDate).toLocaleDateString()}\n`;
  summary += `Status: ${job.status}\n\n`;

  summary += `💰 BUDGET BREAKDOWN\n`;
  summary += `Total Budget: £${job.estimatedPrice.toLocaleString()}\n`;
  summary += `Total Spent: £${totalExpenses.toLocaleString()} (${percentageSpent}%)\n`;
  summary += `Remaining: £${remaining.toLocaleString()}\n\n`;

  if (job.expenses.length > 0) {
    summary += `📊 EXPENSES (${job.expenses.length} items)\n`;
    job.expenses.forEach((exp, index) => {
      summary += `${index + 1}. ${exp.description} - £${exp.amount.toLocaleString()} (${exp.type})\n`;
    });
  } else {
    summary += `No expenses recorded yet.\n`;
  }

  summary += `\n---\nGenerated by Tru Job Tracker`;

  return summary;
};

export const shareJob = async (job: Job): Promise<boolean> => {
  try {
    const summary = generateJobSummary(job);

    await Share.share({
      title: `${job.title} - Job Summary`,
      text: summary,
      dialogTitle: 'Share Job Summary',
    });

    return true;
  } catch (error) {
    console.error('Error sharing job:', error);
    return false;
  }
};
